name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. 루트 디렉토리 의존성 설치
      - name: Install root dependencies
        run: npm install

      # 4. React와 React DOM 명시적 설치
      - name: Install React dependencies
        run: |
          cd app
          npm install react@18.2.0 react-dom@18.2.0

      # 5. React 앱 빌드 (CI 환경변수 무시 설정)
      - name: Build React app
        run: |
          cd app
          npx cross-env CI=false npm run build

      # 6. Electron 앱 빌드
      - name: Build Electron app
        run: npx electron-builder

      # 7. 빌드 결과 업로드
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/
