name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 루트 디렉토리 의존성 설치
      - name: Install root dependencies
        run: npm install

      # app 디렉토리 의존성 설치
      - name: Install app dependencies
        run: cd app && npm install

      # React 앱 빌드
      - name: Build React app
        run: npx cross-env CI=false npm run app-build

      # Electron 앱 빌드 (npx로 실행)
      - name: Build Electron app
        run: npx electron-builder

      # 빌드 결과 업로드
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/
